services:
  chesshub-ui:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: chesshub-ui
    image: ${DOCKER_USERNAME}/chesshub-ui:${DOCKER_IMAGE_VERSION}
    ports:
      - "9000:9000"